# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blinky_monitor}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{James Ottaway}, %q{Mark Ryall}]
  s.date = %q{2011-11-02}
  s.description = %q{watches a CI server and tells blinky about it. dude.}
  s.email = %q{james@ottaway.mp}
  s.executables = [%q{blink}]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/blink",
    "lib/blinky_monitor.rb",
    "lib/blinky_monitor/jenkins_server.rb",
    "lib/blinky_monitor/monitor.rb",
    "spec/blinky.rb",
    "spec/blinky_monitor/jenkins_server_spec.rb",
    "spec/blinky_monitor/monitor_spec.rb",
    "spec/blinky_monitor_spec.rb",
    "spec/rspec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jamesottaway/blinky_monitor}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{watches a CI server and tells blinky about it}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.8"])
      s.add_development_dependency(%q<rspec>, ["~> 2"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<rake>, ["~> 0.8"])
      s.add_dependency(%q<rspec>, ["~> 2"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<rake>, ["~> 0.8"])
    s.add_dependency(%q<rspec>, ["~> 2"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

